/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Executive;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kingston
 */
public class Employees_Management extends javax.swing.JFrame {

    /**
     * Creates new form Employees_Management
     */
    public Employees_Management() {
        initComponents();
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        import_data_btn = new javax.swing.JButton();
        create_new_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        save_data_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));

        import_data_btn.setText("Import Data");
        import_data_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                import_data_btnActionPerformed(evt);
            }
        });

        create_new_btn.setText("Create New ");
        create_new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_new_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Employees Management");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        save_data_btn.setText("Save Data");
        save_data_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_data_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(create_new_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(import_data_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save_data_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(create_new_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(import_data_btn)
                        .addGap(18, 18, 18)
                        .addComponent(save_data_btn)
                        .addGap(18, 18, 18)
                        .addComponent(back_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void import_data_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_data_btnActionPerformed
        // TODO add your handling code here:
        File file = new File ("C:\\Users\\Kingston\\Documents\\NetBeansProjects\\Assignment\\employees_management.txt");
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line = br.readLine();
            String [] colHeadings = line.trim().split(":");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(colHeadings);

            Object [] dataRows = br.lines().toArray(); //it will read all the lines in the file in array
            System.out.println("No of records : "+ dataRows.length);
            for (int i = 0; i < dataRows.length; i++){
                String rec = (dataRows[i].toString());
                String [] dataRow = rec.split(":");
                model.addRow(dataRow);
            } br.close();
        } catch (Exception ex) {
            Logger.getLogger(Employees_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_import_data_btnActionPerformed

    private void create_new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_new_btnActionPerformed
        // TODO add your handling code here:
        close();
        Create_New_Employees cne = new Create_New_Employees();
        cne.setVisible(true);
    }//GEN-LAST:event_create_new_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        close();
        Admin_Executive_Menu aem = new Admin_Executive_Menu();
        aem.setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void save_data_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_data_btnActionPerformed
        // TODO add your handling code here:
        File file = new File ("C:\\Users\\Kingston\\Documents\\NetBeansProjects\\Assignment\\employees_management.txt");
        try {
            String line = "";
            String lines = "";
            int index;
            BufferedWriter bw = new BufferedWriter(new FileWriter(file));
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String colHeadings = "";
            for (int i = 0; i < model.getColumnCount(); i++){
                colHeadings = colHeadings + model.getColumnName(i) + ":" ;
            }

            index = colHeadings.lastIndexOf(":");
            StringBuilder Line = new StringBuilder(colHeadings);
            Line.setCharAt(index, ' ');

            bw.write(Line + "\n");

            for (int row = 0; row < model.getRowCount(); row++){
                for (int col = 0; col < model.getColumnCount(); col++)
                line =  line + model.getValueAt(row, col) + ":" ;
                index = line.lastIndexOf(":");
                Line = new StringBuilder(line);
                Line.setCharAt(index, ' ');
                lines += Line.toString();
                line = "";

                bw.write(Line.toString().trim() + "\n");
            } bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Employees_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_data_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton create_new_btn;
    private javax.swing.JButton import_data_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton save_data_btn;
    // End of variables declaration//GEN-END:variables
}
